name: Deploy Angular Project

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Configure git
        run: |
          git config --global user.email "owtf086@gmail.com"
          git config --global user.name "ilyavtln"

      - name: Build project
        run: ng deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  report-build-status:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Report build status
        run: echo "::notice title=Build and Deploy Status::The build and deploy process is completed."

  display-deployment-link:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Display deployment link
        run: |
          DEPLOYMENT_URL="https://ilyavtln.github.io/test-gh-pages/"
          echo "::notice title=Deployment Complete::Website deployed! Visit it at $DEPLOYMENT_URL"
