name: Deploy Angular App

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

  install:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

  build:
    runs-on: ubuntu-latest
    needs: install

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure git
        run: |
          git config --global user.email "owtf086@gmail.com"
          git config --global user.name "ilyavtln"

      - name: Build project
        run: ng build --prod

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        run: ng deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show deployment link
        run: echo "::notice title=Deployment Complete::Website deployed! Visit it at [https://ilyavtln.github.io/test-gh-pages](https://ilyavtln.github.io/test-gh-pages)"
